export const GENERATE_CELLS = 'GENERATE_CELLS';
export const IS_BOMB_REGENERATE_CELLS = 'IS_BOMB_REGENERATE_CELLS'
export const OPEN_ZERO_CELL = 'OPEN_ZERO_CELL';
export const OPEN_POSITIVE_CELL = 'OPEN_POSITIVE_CELL';
export const MARK_CELL = 'MARK_CELL';
export const UNMARK_CELL = 'UNMARK_CELL';

export const OPEN_MODAL_WINDOW = 'OPEN_MODAL_WINDOW';
export const CLOSE_MODAL_WINDOW = 'CLOSE_MODAL_WINDOW';
export const DECREASE_FLAGS = 'DECREASE_FLAGS';
export const INCREASE_FLAGS = 'INCREASE_FLAGS';
export const START_TIMER = 'START_TIMER';