export const GENERATE_CELLS = 'GENERATE_CELLS';
export const OPEN_ZERO_CELL = 'OPEN_ZERO_CELL';
export const OPEN_POSITIVE_CELL = 'OPEN_POSITIVE_CELL';

export const OPEN_MODAL_WINDOW = 'OPEN_MODAL_WINDOW';
export const CLOSE_MODAL_WINDOW = 'CLOSE_MODAL_WINDOW';